auto-sync opcode & operand encoding info generation
rizinorg/llvm-capstone pull request #14
Opened 2023-06-16 17:57 UTC by AngelDev06

This is the modified llvm-capstone version that I used to generate the encoding info of both opcode and operands of an instruction for the **ARM** architecture. However this version could also be used to generate the required tables for the rest of the auto-sync archs. My modifications are quite simple. I only added two new functions, one called `getCSOperandEncoding` and the other `getCSOpcodeEncoding`. The former is being used on `printInsnOpMapEntry` (so the operand encoding info goes to the InsnMapOp.inc file) while the latter on `printInsnMapEntry`.

2023-06-17 00:25 UTC, XVilka requested changes

2023-06-17 00:25 UTC, XVilka commented on llvm/utils/TableGen/PrinterCapstone.cpp
>    OS << "/* Capstone Disassembly Engine, http://www.capstone-engine.org */\n"
By the way, we should fix the URL(s) to be HTTPS

2023-06-17 13:02 UTC, Rot127 approved these changes
Please fix those comments. But besides that LGTM. Thanks a lot!

2023-06-17 13:02 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    std::array<unsigned, 5> Sizes;
In Capstone the indices and sizes array is of size 8. Please increase the size here and add a check below. If there are more pieces you can exit with something like `PrintFatalNote("Too many operands pieces etc.")` or `llvm_unreachable` or something.

2023-06-17 13:02 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +  if (EncodingData.OperandPiecesCount) {
Please check for
```
if (!EncodingData.OperandPiecesCount)
   return "{ 0 }";
```

So the larger code block is not indented.

2023-06-17 13:02 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +      OpcodeData.Indexes[OpcodeData.BitCount] = InstrBitIdx - StartIdx;
Same as above. Please check for array overflows and fail safely. There is no target (to my knowledge) with >64bit instructions, but who knows what the future brings.

2023-06-17 13:02 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
>    OS << "/* Capstone Disassembly Engine, http://www.capstone-engine.org */\n"
```suggestion
  OS << "/* Capstone Disassembly Engine, https://www.capstone-engine.org */\n"
```

2023-06-17 13:02 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
>    OS << "/* Capstone Disassembly Engine, http://www.capstone-engine.org */\n"
Lets do it here. We will generate all inc files before the next release anyway.

2023-06-17 20:22 UTC, AngelDev06 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    std::array<unsigned, 5> Sizes;
Originally I was writting the code with the mindset that it should only be used for ARM so I added 5 because that's actually the max number of operand pieces you can get. But anyway I fixed it.

2023-06-18 16:03 UTC, XVilka commented
@AngelDev06 please rebase as AArch64 PR was merged and now there are some conflicts

2023-06-19 03:20 UTC, AngelDev06 commented
Done @XVilka

2023-06-19 03:26 UTC, XVilka approved these changes

2023-06-19 09:40 UTC, wargio commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +        OperandType = "CS_OP_IMM";
why not just 
```suggestion
        return "CS_OP_IMM";
    }
    if (OperandType == "OPERAND_PCREL" || OperandType == "OPERAND_IMMEDIATE")
        OperandType = "CS_OP_IMM";
```

2023-06-19 09:42 UTC, wargio approved these changes

2023-06-19 10:41 UTC, Rot127 approved these changes

2023-06-19 10:41 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +  return "{ 0 }";
Please do not remove those brackets. They are necessary. Because without them we get a gazillion warnings from gcc because of this bug from the middle ages:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119

2023-06-20 09:37 UTC, AngelDev06 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +  return "{ 0 }";
I don't recall removing them but anyway it's fixed now

2023-06-20 09:55 UTC, merged