Tblgen capstone backends Alpha
rizinorg/llvm-capstone pull request #17
Opened 2023-07-02 08:48 UTC by R33v0LT

Based on #10

2023-07-02 09:55 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaInstrFormats.td
> +//  let Constraints = "$RFALSE = $RDEST";
Are you planning to add the constraints later? They are used to determine writebacks.

2023-07-02 09:59 UTC, Rot127 commented on llvm/utils/TableGen/AsmMatcherEmitter.cpp
> +    case '(':
Please add a comment here that this is part of our CS changes. When we rebase this onto the newest LLVM release, it is too easy to confuse with LLVM changes.

2023-07-06 10:02 UTC, R33v0LT commented on llvm/utils/TableGen/AsmMatcherEmitter.cpp
> +    case '(':
Done

2023-07-06 10:04 UTC, R33v0LT commented on llvm/lib/Target/Alpha/AlphaInstrFormats.td
> +//  let Constraints = "$RFALSE = $RDEST";
They were already presented on line 178. I've removed this comment

2023-07-18 14:11 UTC, Rot127 requested changes

2023-07-18 14:11 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaInstrInfo.td
> +                      [(set GPRC:$RC, (and (shl GPRC:$RA, (sub 64, (shl GPRC:$RB, 3))), 4294967295))], s_ishf>; //Extract longword high
Please use hexadecimal here instead of decimal.

2023-07-27 07:53 UTC, XVilka commented
@R33v0LT please rebase this one to fix the conflict

2023-08-02 11:18 UTC, Rot127 reviewed
Oversaw the last time the `td` changes. But it should be quickly implemented.
Will take a look at the Capstone side now.

2023-08-02 11:18 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaInstrFormats.td
> +def u64imm  : Operand<i64>;
Please set the `OperandType` field for all of them:
```
def u64imm   : Operand<i32> {
  let OperandType = "OPERAND_IMMEDIATE";
}
```

Otherwise the mapping tables might not get generated properly.

2023-08-02 11:18 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaInstrInfo.td
> +}
For instructions which load or store to/from memory you need to set the `mayLoad = 1` and/or `mayStore = 1` field. Otherwise the `READ/WRITE` atritbutes are missing for later in Capstone.

Also I recommend to add a memory operand definition. This allows you in Capstone to distinguish between normal registers and registers used for memory access. As well as immediate values and immediate values as disponent.

This is how a definition could look like:

```c
def mem_global_addr_disp : Operand<iPTR> {
  let MIOperandInfo = (ops tglobaladdr:$imm, GPRC:$reg);
  let OperandType = "OPERAND_MEMORY";
  // If you want to add them as well, you can define other methods for decoding and printing.
  // They must be implemented in the InstrPrinter and the Disassembler.
  // let PrintMethod = "printMemRegImm34";
  // let DecoderMethod = "decodeMemRI34Operands";
}
```

2023-08-02 11:18 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaRegisterInfo.td
Please move all operand definitions to this file. Also the immediates and memory operands.
This is how it is done for other targets. So we should follow this for consistency.

2023-08-02 11:32 UTC, Rot127 commented on llvm/lib/Target/Alpha/AlphaInstrFormats.td
> +def target : Operand<OtherVT> {}
This one is also missing an `OperandType`

2023-08-07 09:41 UTC, Rot127 approved these changes

2023-08-23 03:00 UTC, XVilka approved these changes

2023-08-23 03:02 UTC, merged