Add LoongArch support
rizinorg/llvm-capstone pull request #47
Opened 2024-05-03 07:34 UTC by jiegec

- Comment out unsupported code
- Fill in operands

2024-05-03 08:06 UTC, Rot127 requested changes
Please, before you continue with this rebase it on top of the LLVM 18 branch from https://github.com/capstone-engine/llvm-capstone/pull/45. There are many bug fixes and it is based on LLVM-18.

Now to the changes:
- Before you proceed, please make sure you have read the architecture about the `auto-sync` updater. I would advice you to read this [blog entry](https://rizin.re/posts/auto-sync/) first and afterward check out the docs about: [the general architecture](https://github.com/capstone-engine/capstone/blob/next/docs/ARCHITECTURE.md), the [auto-sync updater](https://github.com/capstone-engine/capstone/blob/next/docs/AutoSync.md) and lastly the [cpp-translator](https://github.com/capstone-engine/capstone/tree/next/suite/auto-sync/src/autosync/cpptranslator). Last but not least I highly recommend to step with a debugger through a decoding of an ARM, PPC or AArch64 instruction. This way you can see in practice how it is done.
- Please do not make any changes to the LLVM files here. Exceptions are `TableGen` related files. But any target related source code should stay the same. The reason is, that it is a lot and very very annoying work to rebase our patched LLVM code onto the newest release. We need to have as little changes in the original LLVM source code as possible. This is why all our editing of the `LoongArchDisassembler` etc files, all happen in the auto-sync scripts and not here. Because the scritps automate a lot of them and keep the changes in this repo small.

You are one of the first users of the auto-sync updater. So I would love to improve the first steps for people like you. If you could tell me where you got confused I would like to know it, so I can make the "new-user" steps easier.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +// }
You don't need to comment out the unsupported code. With the auto-sync scripts you can choose to not copy them into the Capstone files later (the `Differ` step, see the [docs](https://github.com/capstone-engine/capstone/tree/next/suite/auto-sync/src/autosync/cpptranslator)).

In fact you shouldn't change any `cpp` or `h` files here (exceptions are additions to the `PrinterCapstone/LLVM` and fixes in the `td` files of LoongArch). I elaborate below

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +template <unsigned N, int P>
These default arguments of template arguments should be handled by the [handleDefaultArg](https://github.com/Rot127/llvm-capstone/blob/f21eecd78d9b599d626b5567b9577d1631cd7cba/llvm/utils/TableGen/PrinterCapstone.cpp#L669-L703) function in `PrinterCapstone`.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +DecodeStatus LoongArchDisassembler::LoongArch_LLVM_getInstruction(MCInst &MI, uint64_t &Size,
Renaming is not necessary. `LoongArchDisassembler::getInstruction` is translated to `LoongArchDisassembler_getInstruction` with the auto-sync scripts.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/LoongArchInstrInfo.td
> +  let DecoderMethod = "decodeUImmOperand<12, 0>";
See above

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/MCTargetDesc/LoongArchInstPrinter.cpp
> +  O << '$' << getRegisterName(Reg, LoongArch::RegAliasName);
This change is not necessary either. You can do it later in the C translated version of the file and save the change. Whenever the LoongArch module is updated, the change you made in the C code is automatically applied on the C file.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/MCTargetDesc/LoongArchInstPrinter.cpp
> +    }
Please do not add the detail handling in the code. Every `printOperand` or similar function which handles operands, get a `add_cs_detail(...)` call added in the first line of the function. These functions should be implemented in `LoongArchMapping.c` and all the details are added there.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/MCTargetDesc/LoongArchInstPrinter.cpp
> +  // MO.getExpr()->print(O, &MAI);
The expression code can be later removed in the C translated version of the file.

2024-05-03 08:06 UTC, Rot127 commented on llvm/lib/Target/LoongArch/MCTargetDesc/LoongArchInstPrinter.h
> +  static void printInstruction(const MCInst *MI, uint64_t Address,
`static` should be changed later in the C code as well.

2024-05-03 08:06 UTC, Rot127 commented on llvm/utils/TableGen/CodeGenTarget.cpp
> +  case MVT::INVALID_SIMPLE_VALUE_TYPE: return "MVT::INVALID_SIMPLE_VALUE_TYPE";
The invalid case should been handled. If not, please let me know the error you get.

2024-05-03 08:06 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    OS << "  assert(0 && \"Unknown PrintMethod kind\");\n";
`llvm_unreachable` gets automatically replaced by the translator.

2024-05-03 08:08 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +// }
Thanks, I am more accustomed to generate everything and stick to them. If it is ok to keep out of sync for these files, I will proceed.

2024-05-03 08:08 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +template <unsigned N, int P>
I think I have tried this one before, but it did not support multiple template argument while one of them have default value. I will try again.

2024-05-03 08:09 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +DecodeStatus LoongArchDisassembler::LoongArch_LLVM_getInstruction(MCInst &MI, uint64_t &Size,
It somehow did not translate this for me.

2024-05-03 08:09 UTC, jiegec commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    OS << "  assert(0 && \"Unknown PrintMethod kind\");\n";
The other uses of llvm_unreachable was replaced automatically, but this one was not.

2024-05-03 08:10 UTC, jiegec commented on llvm/utils/TableGen/CodeGenTarget.cpp
> +  case MVT::INVALID_SIMPLE_VALUE_TYPE: return "MVT::INVALID_SIMPLE_VALUE_TYPE";
```
INFO:root:Generating Mapping tables...
DEBUG:root:Generating CCS tables...
DEBUG:root:/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --printerLang=CCS --gen-asm-matcher -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td
ILLEGAL VALUE TYPE!
UNREACHABLE executed at /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/utils/TableGen/CodeGenTarget.cpp:263!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --printerLang=CCS --gen-asm-matcher -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  llvm-tblgen 0x000056bedb92bfa0
1  llvm-tblgen 0x000056bedb92c39a
2  llvm-tblgen 0x000056bedb929e88
3  llvm-tblgen 0x000056bedb92b9cf
4  libc.so.6   0x00007d898dc77050
5  libc.so.6   0x00007d898dcc5e2c
6  libc.so.6   0x00007d898dc76fb2 gsignal + 18
7  libc.so.6   0x00007d898dc61472 abort + 211
```

2024-05-03 08:15 UTC, jiegec commented
I have rebased on top of auto-sync-18 branch and dropped LoongArch-specific changes.

2024-05-03 08:18 UTC, jiegec commented
Using capstone `next` branch and llvm-capstone `auto-sync-18` branch:

```
INFO:root:Generating Disassembler tables...
DEBUG:root:Generating CCS tables...
DEBUG:root:/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --printerLang=CCS --gen-disassembler -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch -o /home/jiegec/capstone/suite/auto-sync/build/llvm_c_inc/LoongArchGenDisassemblerTables.inc /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td
llvm-tblgen: Unknown command line argument '--printerLang=CCS'.  Try: '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --help'
llvm-tblgen: Did you mean '--print-options=CCS'?
CRITICAL:root:Generation failed
Traceback (most recent call last):
  File "/home/jiegec/capstone/suite/auto-sync/./src/autosync/ASUpdater.py", line 263, in <module>
    Updater.update()
  File "/home/jiegec/capstone/suite/auto-sync/./src/autosync/ASUpdater.py", line 141, in update
    self.inc_generator.generate()
  File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 101, in generate
    self.gen_incs()
  File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 177, in gen_incs
    raise e
  File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 171, in gen_incs
    subprocess.run(
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen', '--printerLang=CCS', '--gen-disassembler', '-I', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include', '-I', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch', '-o', '/home/jiegec/capstone/suite/auto-sync/build/llvm_c_inc/LoongArchGenDisassemblerTables.inc', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td']' returned non-zero exit status 1.
```

2024-05-03 08:33 UTC, jiegec commented
> Using capstone `next` branch and llvm-capstone `auto-sync-18` branch:
> 
> ```
> INFO:root:Generating Disassembler tables...
> DEBUG:root:Generating CCS tables...
> DEBUG:root:/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --printerLang=CCS --gen-disassembler -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include -I /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch -o /home/jiegec/capstone/suite/auto-sync/build/llvm_c_inc/LoongArchGenDisassemblerTables.inc /home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td
> llvm-tblgen: Unknown command line argument '--printerLang=CCS'.  Try: '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen --help'
> llvm-tblgen: Did you mean '--print-options=CCS'?
> CRITICAL:root:Generation failed
> Traceback (most recent call last):
>   File "/home/jiegec/capstone/suite/auto-sync/./src/autosync/ASUpdater.py", line 263, in <module>
>     Updater.update()
>   File "/home/jiegec/capstone/suite/auto-sync/./src/autosync/ASUpdater.py", line 141, in update
>     self.inc_generator.generate()
>   File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 101, in generate
>     self.gen_incs()
>   File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 177, in gen_incs
>     raise e
>   File "/home/jiegec/capstone/suite/auto-sync/src/autosync/IncGenerator.py", line 171, in gen_incs
>     subprocess.run(
>   File "/usr/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/build/bin/llvm-tblgen', '--printerLang=CCS', '--gen-disassembler', '-I', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/include', '-I', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch', '-o', '/home/jiegec/capstone/suite/auto-sync/build/llvm_c_inc/LoongArchGenDisassemblerTables.inc', '/home/jiegec/capstone/suite/auto-sync/vendor/llvm_root/llvm/lib/Target/LoongArch/LoongArch.td']' returned non-zero exit status 1.
> ```

Update: oh, I need to use auto-sync-18 from your repo, not capstone-engine.

2024-05-03 08:36 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +template <unsigned N, int P>
```
- #define DEFINE_decodeSImmOperand(N, S) \
+ #define DEFINE_decodeSImmOperand(N, unsigned S = 0) \
-       static DecodeStatus CONCAT(decodeSImmOperand, CONCAT(N, S))( \
+       static DecodeStatus CONCAT(decodeSImmOperand, \
+                                  CONCAT(N, unsigned S = 0))( \
                MCInst * Inst, uint64_t Imm, int64_t Address, \
                const void *Decoder) \
        { \
                MCOperand_CreateImm0(Inst, (SignExtend64((Imm << S), N + S))); \
                return MCDisassembler_Success; \
        }
```

2024-05-03 08:55 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +template <unsigned N, int P>
Oh, I see what you mean. Fixing.

2024-05-03 09:40 UTC, jiegec commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +template <unsigned N, int P>
The missing feature is implemented in the last commit.

2024-05-03 09:51 UTC, Rot127 commented on llvm/lib/Target/LoongArch/Disassembler/LoongArchDisassembler.cpp
> +DecodeStatus LoongArchDisassembler::LoongArch_LLVM_getInstruction(MCInst &MI, uint64_t &Size,
Ah, yes. So the reason is that every arch has this `getInstruction` function. Hence we can not expose it publicly. Because we would get linking conflicts.
Instead you can add the following function by hand to the translated `LoongArchDisassembler.c` file:

```c
DecodeStatus LoongArch_LLVM_getInstruction(csh handle, const uint8_t *Bytes,
				     size_t BytesLen, MCInst *MI,
				     uint16_t *Size, uint64_t Address,
				     void *Info)
{
	return getInstruction(handle, Bytes, BytesLen, MI, Size, Address, Info);
}
```

This function should be declared in the `LoongArchLinkage.h` header file. Same things need to be done for `getRegisterName` and `printInst`. You can check the PPC module as example.

2024-05-03 10:13 UTC, Rot127 commented on llvm/utils/TableGen/CodeGenTarget.cpp
> +  case MVT::INVALID_SIMPLE_VALUE_TYPE: return "MVT::INVALID_SIMPLE_VALUE_TYPE";
Ok, yes. This is actually the best way to fix it for us. Please add a comment like "capstone addition" to it. So we don't get confused when rebasing.

During looking into it I figured that the `bare_symbol` operand has no `OperandType` assigned. This procudes invalid operand details in the mapping tables like this:
```
...
  { CS_OP_INVALID, CS_AC_READ, { CS_DATA_TYPE_INVALID_SIMPLE_VALUE_TYPE, CS_DATA_TYPE_LAST } }, /* imm */
...
```
It should be an immediate I guess?

If yes, please apply this patch as well:
```diff
diff --git a/llvm/lib/Target/LoongArch/LoongArchInstrInfo.td b/llvm/lib/Target/LoongArch/LoongArchInstrInfo.td
index ae73a8ac74c7..af62cf9e74a0 100644
--- a/llvm/lib/Target/LoongArch/LoongArchInstrInfo.td
+++ b/llvm/lib/Target/LoongArch/LoongArchInstrInfo.td
@@ -450,6 +450,7 @@ def BareSymbol : AsmOperandClass {
 // A bare symbol used in "PseudoLA_*" instructions.
 def bare_symbol : Operand<GRLenVT> {
   let ParserMatchClass = BareSymbol;
+  let OperandType = "OPERAND_IMMEDIATE";
 }
 
 // Standalone (codegen-only) immleaf patterns.
```

2024-05-03 10:14 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    OS << "  assert(0 && \"Unknown PrintMethod kind\");\n";
Sorry, where is is my mind. All good with this change.

2024-05-03 10:16 UTC, Rot127 commented
Also please add LoongArch to the [CI](https://github.com/capstone-engine/llvm-capstone/tree/auto-sync/.github/workflows)

2024-05-03 11:16 UTC, jiegec commented on llvm/utils/TableGen/CodeGenTarget.cpp
> +  case MVT::INVALID_SIMPLE_VALUE_TYPE: return "MVT::INVALID_SIMPLE_VALUE_TYPE";
Done

2024-05-03 13:11 UTC, jiegec commented on llvm/utils/TableGen/CodeGenTarget.cpp
> +  case MVT::INVALID_SIMPLE_VALUE_TYPE: return "MVT::INVALID_SIMPLE_VALUE_TYPE";
I also discovered that most immediate operands are not flagged as `OPERAND_IMMEDIATE`, so I add them in the following commit.

2024-05-15 04:26 UTC, Rot127 requested changes

2024-05-15 04:26 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    MemoryAccess = "CS_AC_READ_WRTE";
Typo in `CS_AC_READ_WRTE` (missing `I` in `WRITE`)

2024-05-15 15:45 UTC, jiegec commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    MemoryAccess = "CS_AC_READ_WRTE";
It comes from the following enum:

```c++
typedef enum cs_ac_type {
	CS_AC_INVALID = 0,    ///< Uninitialized/invalid access type.
	CS_AC_READ = 1 << 0,  ///< Operand read from memory or register.
	CS_AC_WRITE = 1 << 1, ///< Operand write to memory or register.
	CS_AC_READ_WRTE =
		CS_AC_READ |
		CS_AC_WRITE, ///< Operand reads and writes from/to memory or register.
} cs_ac_type;
```

2024-05-16 05:28 UTC, Rot127 commented on llvm/utils/TableGen/PrinterCapstone.cpp
> +    MemoryAccess = "CS_AC_READ_WRTE";
Ah, well. This is a typo. Get's fixed here: https://github.com/capstone-engine/capstone/pull/2358

2024-05-29 08:32 UTC, Rot127 commented
Merged with https://github.com/capstone-engine/llvm-capstone/pull/45

2024-05-29 08:32 UTC, closed without merging